<?php 
/*
   Generated by Manuigniter v2.0 
   www.manuigniter.com
*/
class IV_inventory_model extends CI_Model 
{ 
     function __construct()
      {
          parent::__construct();
      }
      /*
        * Get IV_inventory by inventory_id 
      */ 
      function get_IV_inventory($inventory_id)
      {
        try{
           return $this->db->get_where('IV_inventory',array('inventory_id'=>$inventory_id))->row_array();
           } catch (Exception $ex) {
             throw new Exception('IV_inventory_model Model : Error in get_IV_inventory function - ' . $ex);
           }  
      }
      /*
        * Get IV_inventory by  column name
      */ 
      function get_IV_inventorybyclm_name($clm_name,$clm_value)
      {
        try{
           return $this->db->get_where('IV_inventory',array($clm_name=>$clm_value))->row_array();
           } catch (Exception $ex) {
             throw new Exception('IV_inventory_model Madel : Error in get_IV_inventorybyclm_name function - ' . $ex);
           }  
      }
     /*
        * Get All IV_inventory count 
      */ 
      function get_all_IV_inventory_count()
      {
        try{
           $this->db->from('IV_inventory');
           return $this->db->count_all_results();
           } catch (Exception $ex) {
             throw new Exception('IV_inventory_model model : Error in get_all_IV_inventory_count function - ' . $ex);
           }  
      }
     /*
        * Get All with associated tables join IV_inventorycount 
      */ 
      function get_all_with_asso_IV_inventory()
      {
        try{
           $this->db->select('*');
           $this->db->from('IV_inventory a  ' );
            $this->db->join('IV_products b', 'b.product_id=a. product_id','left');
            $this->db->join('IV_supply c', 'c.supply_id=a. supply_id','left');
          $query = $this->db->get(); 
            if($query->num_rows() != 0){
               return $query->result_array();
            }else{
                return false;
            }
           } catch (Exception $ex) {
             throw new Exception('IV_inventory_model model : Error in get_all_with_asso_IV_inventory function - ' . $ex);
           }  
      }
      /*
          * Get all IV_inventory 
      */ 
      function get_all_IV_inventory($id=null)
      {
        try{
              $this->db->select("IV_inventory.*,iv_products.*,iv_supply.description,SUM(IV_inventory.quantity) AS SumQ");
              $this->db->order_by('inventory_id', 'desc');
              $this->db->group_by('IV_inventory.product_id');
              $this->db->join('iv_products', 'IV_inventory.product_id	 = iv_products.product_id', 'inner');
              $this->db->join('iv_supply', 'IV_inventory.supply_id	 = iv_supply.supply_id', 'inner');
              if($id!=null){
                $this->db->where('IV_inventory.owner_id',$id);
               }
               return $this->db->get('IV_inventory')->result_array();
           } catch (Exception $ex) {
             throw new Exception('IV_inventory_model model : Error in get_all_IV_inventory function - ' . $ex);
           }  
      } 
      /*
         * function to add new IV_inventory 
      */
      function add_IV_inventory($params)
      {
        try{
          $this->db->insert('IV_inventory',$params);
        return $this->db->insert_id();
           } catch (Exception $ex) {
             throw new Exception('IV_inventory_model model : Error in add_IV_inventory function - ' . $ex);
           }  
      }
      /* 
          * function to update IV_inventory 
      */
      function update_IV_inventory($inventory_id,$params)
      {
        try{
            $this->db->where('inventory_id',$inventory_id);
        return $this->db->update('IV_inventory',$params);
           } catch (Exception $ex) {
             throw new Exception('IV_inventory_model model : Error in update_IV_inventory function - ' . $ex);
           }  
       }
     /* 
          * function to delete IV_inventory 
      */
       function delete_IV_inventory($inventory_id)
       {
        try{
             return $this->db->delete('IV_inventory',array('inventory_id'=>$inventory_id));
           } catch (Exception $ex) {
             throw new Exception('IV_inventory_model model : Error in delete_IV_inventory function - ' . $ex);
           }  
       }
      /*
        * Get IV_inventory by  column name where not in particular id
      */ 
      function get_IV_inventorybyclm_name_not_id($clm_name,$clm_value,$where_cond)
      {
        try{
            $this->db->where('inventory_id!=', $where_cond);
           return $this->db->get_where('IV_inventory',array($clm_name=>$clm_value))->row_array();
           } catch (Exception $ex) {
             throw new Exception('IV_inventory_model model : Error in get_IV_inventorybyclm_name_not_id function - ' . $ex);
           }  
      }
     /*
        * Get All with associated tables join IV_inventorycount 
      */ 
      function get_all_with_asso_IV_inventory_by_cat($column_name=null,$value_id=null,$params=array())
      {
        try{
           $this->db->select('*');
           $this->db->from('IV_inventory a  ' );
              //$this->db->where($column_name, $value_id);
            $this->db->join('IV_products b', 'b.product_id=a. product_id','left');
              $this->db->where('a.'.$column_name, $value_id);
            $this->db->join('IV_supply c', 'c.supply_id=a. supply_id','left');
              $this->db->where('a.'.$column_name, $value_id);
          $query = $this->db->get(); 
            if($query->num_rows() != 0){
               return $query->result_array();
            }else{
                return false;
            }
           } catch (Exception $ex) {
             throw new Exception('IV_inventory_model model : Error in get_all_with_asso_IV_inventory_by_cat function - ' . $ex);
           }  
      }
      /*
          * Get all IV_inventory_by_cat 
      */ 
      function get_all_IV_inventory_by_cat($column_name=null,$value_id=null,$params=array())
      {
        try{
              $this->db->order_by('inventory_id', 'desc');
              $this->db->where($column_name, $value_id);
              if(isset($params) && !empty($params)){
               $this->db->limit($params['limit'], $params['offset']);
              }
               return $this->db->get('IV_inventory')->result_array();
           } catch (Exception $ex) {
             throw new Exception('IV_inventory_model model : Error in get_all_IV_inventory_by_cat function - ' . $ex);
           }  
      } 
 }
