<?php 
/*
   Generated by Manuigniter v2.0 
   www.manuigniter.com
*/
class IV_products_model extends CI_Model 
{ 
     function __construct()
      {
          parent::__construct();
      }
      /*
        * Get IV_products by product_id 
      */ 
      function get_IV_products($product_id)
      {
        try{
           return $this->db->get_where('IV_products',array('product_id'=>$product_id))->row_array();
           } catch (Exception $ex) {
             throw new Exception('IV_products_model Model : Error in get_IV_products function - ' . $ex);
           }  
      }
      /*
        * Get IV_products by  column name
      */ 
      function get_IV_productsbyclm_name($clm_name,$clm_value)
      {
        try{
           return $this->db->get_where('IV_products',array($clm_name=>$clm_value))->row_array();
           } catch (Exception $ex) {
             throw new Exception('IV_products_model Madel : Error in get_IV_productsbyclm_name function - ' . $ex);
           }  
      }
     /*
        * Get All IV_products count 
      */ 
      function get_all_IV_products_count()
      {
        try{
           $this->db->from('IV_products');
           return $this->db->count_all_results();
           } catch (Exception $ex) {
             throw new Exception('IV_products_model model : Error in get_all_IV_products_count function - ' . $ex);
           }  
      }
     /*
        * Get All with associated tables join IV_productscount 
      */ 
      function get_all_with_asso_IV_products()
      {
        try{
           $this->db->select('*');
           $this->db->from('IV_products a  ' );
            $this->db->join('IV_categories b', 'b.category_id=a. category_id','left');
          $query = $this->db->get(); 
            if($query->num_rows() != 0){
               return $query->result_array();
            }else{
                return false;
            }
           } catch (Exception $ex) {
             throw new Exception('IV_products_model model : Error in get_all_with_asso_IV_products function - ' . $ex);
           }  
      }
      /*
          * Get all IV_products 
      */ 
      function get_all_IV_products($params = array())
      {
        try{
              $this->db->order_by('product_id', 'desc');
              $this->db->join('iv_categories', 'IV_products.category_id = iv_categories.category_id', 'inner');
              if(isset($params) && !empty($params)){
               $this->db->limit($params['limit'], $params['offset']);
              }
               return $this->db->get('IV_products')->result_array();
           } catch (Exception $ex) {
             throw new Exception('IV_products_model model : Error in get_all_IV_products function - ' . $ex);
           }  
      } 
      /*
         * function to add new IV_products 
      */
      function add_IV_products($params)
      {
        try{
          $this->db->insert('IV_products',$params);
        return $this->db->insert_id();
           } catch (Exception $ex) {
             throw new Exception('IV_products_model model : Error in add_IV_products function - ' . $ex);
           }  
      }
      /* 
          * function to update IV_products 
      */
      function update_IV_products($product_id,$params)
      {
        try{
            $this->db->where('product_id',$product_id);
        return $this->db->update('IV_products',$params);
           } catch (Exception $ex) {
             throw new Exception('IV_products_model model : Error in update_IV_products function - ' . $ex);
           }  
       }
     /* 
          * function to delete IV_products 
      */
       function delete_IV_products($product_id)
       {
        try{
             return $this->db->delete('IV_products',array('product_id'=>$product_id));
           } catch (Exception $ex) {
             throw new Exception('IV_products_model model : Error in delete_IV_products function - ' . $ex);
           }  
       }
      /*
        * Get IV_products by  column name where not in particular id
      */ 
      function get_IV_productsbyclm_name_not_id($clm_name,$clm_value,$where_cond)
      {
        try{
            $this->db->where('product_id!=', $where_cond);
           return $this->db->get_where('IV_products',array($clm_name=>$clm_value))->row_array();
           } catch (Exception $ex) {
             throw new Exception('IV_products_model model : Error in get_IV_productsbyclm_name_not_id function - ' . $ex);
           }  
      }
     /*
        * Get All with associated tables join IV_productscount 
      */ 
      function get_all_with_asso_IV_products_by_cat($column_name=null,$value_id=null,$params=array())
      {
        try{
           $this->db->select('*');
           $this->db->from('IV_products a  ' );
              //$this->db->where($column_name, $value_id);
            $this->db->join('IV_categories b', 'b.category_id=a. category_id','left');
              $this->db->where('a.'.$column_name, $value_id);
          $query = $this->db->get(); 
            if($query->num_rows() != 0){
               return $query->result_array();
            }else{
                return false;
            }
           } catch (Exception $ex) {
             throw new Exception('IV_products_model model : Error in get_all_with_asso_IV_products_by_cat function - ' . $ex);
           }  
      }
      /*
          * Get all IV_products_by_cat 
      */ 
      function get_all_IV_products_by_cat($column_name=null,$value_id=null,$params=array())
      {
        try{
              $this->db->order_by('product_id', 'desc');
              $this->db->where($column_name, $value_id);
              if(isset($params) && !empty($params)){
               $this->db->limit($params['limit'], $params['offset']);
              }
               return $this->db->get('IV_products')->result_array();
           } catch (Exception $ex) {
             throw new Exception('IV_products_model model : Error in get_all_IV_products_by_cat function - ' . $ex);
           }  
      } 
 }
