<?php 
/*
   Generated by Manuigniter v2.0 
   www.manuigniter.com
*/
class IV_supply_model extends CI_Model 
{ 
     function __construct()
      {
          parent::__construct();
      }
      /*
        * Get IV_supply by supply_id 
      */ 
      function get_IV_supply($supply_id)
      {
        try{
           return $this->db->get_where('IV_supply',array('supply_id'=>$supply_id))->row_array();
           } catch (Exception $ex) {
             throw new Exception('IV_supply_model Model : Error in get_IV_supply function - ' . $ex);
           }  
      }
      /*
        * Get IV_supply by  column name
      */ 
      function get_IV_supplybyclm_name($clm_name,$clm_value)
      {
        try{
           return $this->db->get_where('IV_supply',array($clm_name=>$clm_value))->row_array();
           } catch (Exception $ex) {
             throw new Exception('IV_supply_model Madel : Error in get_IV_supplybyclm_name function - ' . $ex);
           }  
      }
     /*
        * Get All IV_supply count 
      */ 
      function get_all_IV_supply_count()
      {
        try{
           $this->db->from('IV_supply');
           return $this->db->count_all_results();
           } catch (Exception $ex) {
             throw new Exception('IV_supply_model model : Error in get_all_IV_supply_count function - ' . $ex);
           }  
      }
     /*
        * Get All with associated tables join IV_supplycount 
      */ 
      function get_all_with_asso_IV_supply()
      {
        try{
          $query = $this->db->get(); 
            if($query->num_rows() != 0){
               return $query->result_array();
            }else{
                return false;
            }
           } catch (Exception $ex) {
             throw new Exception('IV_supply_model model : Error in get_all_with_asso_IV_supply function - ' . $ex);
           }  
      }
      /*
          * Get all IV_supply 
      */ 
      function get_all_IV_supply($id=null)
      {
        try{
              $this->db->order_by('supply_id', 'desc');
              if($id!=null){
                $this->db->where('owner_id',$id);
               }
               return $this->db->get('IV_supply')->result_array();
           } catch (Exception $ex) {
             throw new Exception('IV_supply_model model : Error in get_all_IV_supply function - ' . $ex);
           }  
      } 
      /*
         * function to add new IV_supply 
      */
      function add_IV_supply($params)
      {
        try{
          $this->db->insert('IV_supply',$params);
        return $this->db->insert_id();
           } catch (Exception $ex) {
             throw new Exception('IV_supply_model model : Error in add_IV_supply function - ' . $ex);
           }  
      }
      /* 
          * function to update IV_supply 
      */
      function update_IV_supply($supply_id,$params)
      {
        try{
            $this->db->where('supply_id',$supply_id);
        return $this->db->update('IV_supply',$params);
           } catch (Exception $ex) {
             throw new Exception('IV_supply_model model : Error in update_IV_supply function - ' . $ex);
           }  
       }
     /* 
          * function to delete IV_supply 
      */
       function delete_IV_supply($supply_id)
       {
        try{
             return $this->db->delete('IV_supply',array('supply_id'=>$supply_id));
           } catch (Exception $ex) {
             throw new Exception('IV_supply_model model : Error in delete_IV_supply function - ' . $ex);
           }  
       }
      /*
        * Get IV_supply by  column name where not in particular id
      */ 
      function get_IV_supplybyclm_name_not_id($clm_name,$clm_value,$where_cond)
      {
        try{
            $this->db->where('supply_id!=', $where_cond);
           return $this->db->get_where('IV_supply',array($clm_name=>$clm_value))->row_array();
           } catch (Exception $ex) {
             throw new Exception('IV_supply_model model : Error in get_IV_supplybyclm_name_not_id function - ' . $ex);
           }  
      }
     /*
        * Get All with associated tables join IV_supplycount 
      */ 
      function get_all_with_asso_IV_supply_by_cat($column_name=null,$value_id=null,$params=array())
      {
        try{
          $query = $this->db->get(); 
            if($query->num_rows() != 0){
               return $query->result_array();
            }else{
                return false;
            }
           } catch (Exception $ex) {
             throw new Exception('IV_supply_model model : Error in get_all_with_asso_IV_supply_by_cat function - ' . $ex);
           }  
      }
      /*
          * Get all IV_supply_by_cat 
      */ 
      function get_all_IV_supply_by_cat($column_name=null,$value_id=null,$params=array())
      {
        try{
              $this->db->order_by('supply_id', 'desc');
              $this->db->where($column_name, $value_id);
              if(isset($params) && !empty($params)){
               $this->db->limit($params['limit'], $params['offset']);
              }
               return $this->db->get('IV_supply')->result_array();
           } catch (Exception $ex) {
             throw new Exception('IV_supply_model model : Error in get_all_IV_supply_by_cat function - ' . $ex);
           }  
      } 
 }
