<?php 
/*
   Generated by Manuigniter v2.0 
   www.manuigniter.com
*/
class Users_model extends CI_Model 
{ 
     function __construct()
      {
          parent::__construct();
      }
      /*
        * Get IV_account by account_id 
      */ 
      function get_userlogin($email,$password)
      {
        try{
           return $this->db->get_where('iv_users',array('email'=>$email,'password'=>$password))->row_array();
           } catch (Exception $ex) {
             throw new Exception('Users Model : Error in get user function - ' . $ex);
           }  
      }
      function get_user($id)
      {
        try{
           return $this->db->get_where('iv_users',array('user_id'=>$id))->row_array();
           } catch (Exception $ex) {
             throw new Exception('Users Model : Error in get user function - ' . $ex);
           }  
      }
      function get_all_keys()
      {
        try{
              $this->db->order_by('key_id', 'asc');
               return $this->db->get('dbkeys')->result_array();
           } catch (Exception $ex) {
             throw new Exception('DBKeys model : Error in get all dbkeys function - ' . $ex);
           }  
      }
     /*
        * Get All users count 
      */ 
      function get_all_users_count()
      {
        try{
           $this->db->from('iv_users');
           return $this->db->count_all_results();
           } catch (Exception $ex) {
             throw new Exception('Users model : Error in get all users function - ' . $ex);
           }  
      }
      
      /*
         * function to add new user 
      */
      function add_User($params)
      {
        try{
          $this->db->insert('iv_users',$params);
        return $this->db->insert_id();
           } catch (Exception $ex) {
             throw new Exception('Users model : Error in add_user function - ' . $ex);
           }  
      }
      /* 
          * function to update IV_account 
      */
      function update_User($id,$params)
      {
        try{
            $this->db->where('user_id',$id);
        return $this->db->update('iv_users',$params);
           } catch (Exception $ex) {
             throw new Exception('Users model : Error in update_user function - ' . $ex);
           }  
       }
     /* 
          * function to delete IV_account 
      */
       function delete_user($id)
       {
        try{
             return $this->db->delete('iv_users',array('user_id'=>$id));
           } catch (Exception $ex) {
             throw new Exception('Users model : Error in delete_users function - ' . $ex);
           }  
       }
     function checktoken($token)
     {
      try{
        return $this->db->get_where('iv_users',array('token'=>$token))->row_array();
        } catch (Exception $ex) {
          throw new Exception('Users Model : Error in get token function - ' . $ex);
        }  
     }
 }
